N,X,Y=map(int, input().split())
A=list(map(int, input().split()))
B=list(map(int, input().split()))
countA=0
countB=0
a=0
b=0
i=0
A,B=zip(*sorted(zip(A,B)))
while i<N and a<=X:
    a+=A[N-i-1]
    countA+=1
    i+=1
B,A=zip(*sorted(zip(B,A)))
i=0
while i<N and b<=Y:
    b+=B[N-i-1]
    countB+=1
    i+=1
print(min(countA,countB))